---
title: "Lightening Round Essays"
format: html
editor: visual
---

**Answer each of the following questions with *one sentence* including a brief explanation.**

1.  Finish the sentence with another student’s name: "If \[Name of Student\] doesn’t earn an A, then nobody should, because..." Explain your choice and your reasoning.

    ???????

2.  What was the most difficult part of the class for you? List a general topic, a specific problem, a kind of work we did, etc. and explain why.

    I struggled with the check-in assignments because I found it hard to learn from the textbook and had a much easier time understanding from the in-class lecture.

3.  What was the easiest part of the class for you? Explain why.

    I found the code-formatting and peer review of code to be the easiest because I have a strong attention to detail.

4.  What part of the class surprised or interested you the most? Explain why.

    I was surprised by how much I learned by the end of the quarter and how I was able to apply the skills I used in this class to my senior project!

5.  Give one piece of advice to a student just beginning a quarter of STAT 331 that will help them be successful in learning.

    Use the handouts in class to take quality notes to use a reference for future problems! They highlight the most important information and is a great resource for the labs.
